'use client'

import {useEffect,useState,useMemo} from 'react'
import Workflows from '@/components/workflows'
import GuestDashboard from '@/components/guest-dashboard'
import {createClient} from '@/lib/supabase/client'

type Tab='Overview'|'Creator Identity'|'Brand Brain'|'Content Studio'|'Approval'|'Social Scheduler'|'Analytics'|'Billing'
const tabs:Tab[]=['Overview','Creator Identity','Brand Brain','Content Studio','Approval','Social Scheduler','Analytics','Billing']

export default function Home(){
 const supabase=useMemo(()=>createClient(),[]); const [user,setUser]=useState<any>(null); const [workspace,setWorkspace]=useState<any>(null); const [credits,setCredits]=useState(0); const [message,setMessage]=useState(''); const [tab,setTab]=useState<Tab>('Overview'); const [stats,setStats]=useState<any>({}); const [items,setItems]=useState<any[]>([]); const [form,setForm]=useState<any>({name:'',description:'',positioning:'',title:'',brief:'',content_type:'social_post'})
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user);if(data.user)loadWorkspace()});const {data:s}=supabase.auth.onAuthStateChange((_e,session)=>{setUser(session?.user??null);if(session?.user)setTimeout(loadWorkspace,0);else{setWorkspace(null);setItems([]);setCredits(0);setStats({})}});return()=>s.subscription.unsubscribe()},[])
 useEffect(()=>{if(workspace)loadTab()},[tab,workspace])
 async function loadWorkspace(){const {data}=await supabase.from('workspace_members').select('workspace_id,role,workspaces(id,name,slug)').limit(1).maybeSingle();if(data){const w:any=(data as any).workspaces;setWorkspace(w);const {data:b}=await supabase.rpc('workspace_credit_balance',{p_workspace_id:w.id});setCredits(Number(b||0));const {data:d}=await supabase.rpc('workspace_dashboard',{p_workspace_id:w.id});setStats(d||{})}}
 async function loadTab(){let table='';if(tab==='Creator Identity')table='creator_identities';if(tab==='Brand Brain')table='brand_brains';if(tab==='Content Studio')table='content_projects';if(tab==='Approval')table='approvals';if(tab==='Social Scheduler')table='scheduled_posts';if(tab==='Analytics')table='analytics_snapshots';if(!table||['Approval','Social Scheduler','Analytics','Billing'].includes(tab)){setItems([]);return}const {data,error}=await supabase.from(table).select('*').eq('workspace_id',workspace.id).order('created_at',{ascending:false}).limit(30);if(error)setMessage(error.message);setItems(data||[])}
 async function createIdentity(){if(!form.name.trim()){setMessage('Nhập tên creator');return}const {error}=await supabase.from('creator_identities').insert({workspace_id:workspace.id,name:form.name,description:form.description,identity_config:{type:'personal_or_virtual_kol'},created_by:user.id});setMessage(error?error.message:'Creator Identity đã được tạo.');if(!error){setForm({...form,name:'',description:''});loadTab();loadWorkspace()}}
 async function createBrain(){if(!form.name.trim()){setMessage('Nhập tên thương hiệu');return}const {error}=await supabase.from('brand_brains').insert({workspace_id:workspace.id,name:form.name,positioning:form.positioning,voice_guidelines:{tone:'authentic, useful, consistent'},visual_guidelines:{system:'brand-controlled'},audience:{description:'defined by creator'},prohibited_content:[],created_by:user.id});setMessage(error?error.message:'Brand Brain đã được tạo.');if(!error){setForm({...form,name:'',positioning:''});loadTab();loadWorkspace()}}
 async function createContent(){if(!form.title.trim()||!form.brief.trim()){setMessage('Nhập tiêu đề và nội dung đầy đủ');return}const {error}=await supabase.from('content_projects').insert({workspace_id:workspace.id,title:form.title,brief:form.brief,content_type:form.content_type,status:'draft',created_by:user.id});setMessage(error?error.message:'Content project đã được tạo.');if(!error){setForm({...form,title:'',brief:''});loadTab();loadWorkspace()}}
 if(!user||!workspace)return <GuestDashboard/>
 const editor=tab==='Creator Identity'?<><h2>Tạo Creator / KOL</h2><input className="field" placeholder="Tên creator" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><textarea className="field" placeholder="Mô tả identity, chuyên môn, phong cách..." value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="btn" onClick={createIdentity}>Lưu Creator Identity</button></>:tab==='Brand Brain'?<><h2>Tạo Brand Brain</h2><input className="field" placeholder="Tên brand system" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><textarea className="field" placeholder="Định vị thương hiệu" value={form.positioning} onChange={e=>setForm({...form,positioning:e.target.value})}/><button className="btn" onClick={createBrain}>Lưu Brand Brain</button></>:tab==='Content Studio'?<><h2>Tạo Content Project</h2><input className="field" placeholder="Tiêu đề" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea className="field" placeholder="Nội dung đầy đủ để gửi duyệt và đăng" value={form.brief} onChange={e=>setForm({...form,brief:e.target.value})}/><select className="field" value={form.content_type} onChange={e=>setForm({...form,content_type:e.target.value})}><option value="social_post">Social post</option><option value="video_script">Video script</option><option value="carousel">Carousel</option><option value="short_video">Short video</option></select><button className="btn" onClick={createContent}>Tạo project</button></>:null
 return <div className="shell"><aside className="side"><div className="brand"><span>SPART</span> CREATOR OS</div><nav className="nav" aria-label="Menu">{tabs.map(t=><button type="button" key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setMessage('')}}>{t}</button>)}</nav></aside><main className="main"><header className="top"><div><div className="eyebrow">Workspace / {workspace.name}</div><h1 className="title">{tab}</h1><div className="muted">Identity → Brand Brain → Content → Approval → Publish → Analytics.</div></div><button className="btn" onClick={()=>supabase.auth.signOut()}>Đăng xuất</button></header>{message&&<div className="status">{message}</div>}{tab==='Overview'?<><section className="grid"><div className="card"><div className="muted">AI Credits</div><div className="metric">{credits}</div><span className="pill">Free plan</span></div><div className="card"><div className="muted">Creator identities</div><div className="metric">{stats.creator_identities||0}</div></div><div className="card"><div className="muted">Content projects</div><div className="metric">{stats.content_projects||0}</div></div><div className="card"><div className="muted">Scheduled posts</div><div className="metric">{stats.scheduled_posts||0}</div></div></section><section className="actions"><div className="card action"><span className="pill">01 Identity</span><h3>Creator Identity</h3><p className="muted">Master identity và cấu hình KOL.</p></div><div className="card action"><span className="pill">02 Content</span><h3>Content Studio</h3><p className="muted">Quản lý production pipeline.</p></div><div className="card action"><span className="pill">03 Distribute</span><h3>Social Scheduler</h3><p className="muted">Lịch xuất bản đa kênh.</p></div></section></>:['Approval','Social Scheduler','Analytics','Billing'].includes(tab)?<Workflows workspaceId={workspace.id} tab={tab} onChanged={loadWorkspace}/>:<section className="card" style={{marginTop:28}}>{editor||<><h2>{tab}</h2><p className="muted">Module đã kết nối database production. {tab==='Social Scheduler'?'Kết nối nhà cung cấp social để bật auto-publish.':''}</p></>}{items.length>0&&<div style={{marginTop:24}}>{items.map((x:any)=><div className="status" key={x.id}><b>{x.name||x.title||x.provider||x.status}</b><div className="muted">{x.description||x.positioning||x.brief||x.status||''}</div></div>)}</div>}</section>}</main></div>
}
