'use client'

import { useEffect,useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export default function Home(){
 const supabase=createClient(); const [email,setEmail]=useState(''); const [user,setUser]=useState<any>(null); const [workspace,setWorkspace]=useState<any>(null); const [credits,setCredits]=useState<number>(0); const [name,setName]=useState('My Creator Brand'); const [message,setMessage]=useState('')
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user);if(data.user) loadWorkspace()});const {data:s}=supabase.auth.onAuthStateChange((_e,session)=>{setUser(session?.user??null);if(session?.user) setTimeout(loadWorkspace,0)});return()=>s.subscription.unsubscribe()},[])
 async function loadWorkspace(){const {data}=await supabase.from('workspace_members').select('workspace_id,role,workspaces(id,name,slug)').limit(1).maybeSingle();if(data){const w:any=(data as any).workspaces;setWorkspace(w);const {data:b}=await supabase.rpc('workspace_credit_balance',{p_workspace_id:w.id});setCredits(Number(b||0))}}
 async function magic(){setMessage('Đang gửi link đăng nhập...');const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});setMessage(error?error.message:'Đã gửi magic link. Hãy kiểm tra email.')}
 async function createWorkspace(){const slug=(name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Math.random().toString(36).slice(2,6)).slice(0,49);const {data,error}=await supabase.rpc('create_workspace',{p_name:name,p_slug:slug});if(error)setMessage(error.message);else{setMessage('Workspace đã được tạo.');await loadWorkspace()}}
 if(!user)return <main className="main"><section className="login card"><div className="eyebrow">SPART AI</div><h1 className="title">Creator OS</h1><p className="muted">Xây thương hiệu cá nhân hoặc KOL ảo, sản xuất nội dung và vận hành social trong một hệ thống.</p><input className="field" placeholder="Email của bạn" value={email} onChange={e=>setEmail(e.target.value)}/><button className="btn" onClick={magic}>Đăng nhập bằng Magic Link</button>{message&&<div className="status">{message}</div>}</section></main>
 if(!workspace)return <main className="main"><section className="login card"><div className="eyebrow">Bước 1 / Onboarding</div><h1>Tạo Creator Workspace</h1><p className="muted">Workspace sẽ chứa Brand Brain, nhân vật, nội dung, social channels và analytics của bạn.</p><input className="field" value={name} onChange={e=>setName(e.target.value)}/><button className="btn" onClick={createWorkspace}>Tạo workspace + nhận 500 credits</button>{message&&<div className="status">{message}</div>}</section></main>
 return <div className="shell"><aside className="side"><div className="brand"><span>SPART</span> CREATOR OS</div><nav className="nav"><a className="active">Overview</a><a>Creator Identity</a><a>Brand Brain</a><a>Content Studio</a><a>Approval</a><a>Social Scheduler</a><a>Analytics</a><a>Billing</a></nav></aside><main className="main"><header className="top"><div><div className="eyebrow">Workspace / {workspace.name}</div><h1 className="title">Creator Command Center</h1><div className="muted">Từ identity → content → approval → publishing → analytics.</div></div><button className="btn" onClick={()=>supabase.auth.signOut()}>Đăng xuất</button></header><section className="grid"><div className="card"><div className="muted">AI Credits</div><div className="metric">{credits}</div><span className="pill">Free plan</span></div><div className="card"><div className="muted">Creator identities</div><div className="metric">0</div></div><div className="card"><div className="muted">Content projects</div><div className="metric">0</div></div><div className="card"><div className="muted">Scheduled posts</div><div className="metric">0</div></div><div className="card wide"><div className="eyebrow">Operating loop</div><h2>One creator. Every channel.</h2><p className="muted">Khóa nhận diện nhân vật, Brand Brain và giọng điệu trước khi scale nội dung. Mọi nội dung đi qua approval trước khi vào lịch đăng.</p></div><div className="card wide"><div className="eyebrow">Production</div><h2>Backend đã kết nối Supabase</h2><p className="muted">Workspace isolation bằng RLS, private asset storage, subscription và immutable credit ledger đã sẵn sàng.</p></div></section><section className="actions"><div className="card action"><span className="pill">01 Identity</span><h3>Tạo Creator / KOL ảo</h3><p className="muted">Master face, character sheet, expression library và asset vault.</p></div><div className="card action"><span className="pill">02 Content</span><h3>Content Studio</h3><p className="muted">Idea → script → caption → creative variants → approval.</p></div><div className="card action"><span className="pill">03 Distribute</span><h3>Social Scheduler</h3><p className="muted">Kết nối kênh, lên lịch và tự động xuất bản nội dung.</p></div></section></main></div>
}
